# Generated by Django 3.2.12 on 2024-02-03 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_flag', models.BooleanField()),
                ('score_1', models.IntegerField()),
                ('score_2', models.IntegerField()),
                ('score_3', models.IntegerField()),
                ('score_4', models.IntegerField()),
                ('score_5', models.IntegerField()),
                ('comment', models.TextField()),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='comics.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
